[build]
builder = "NIXPACKS"
nixpacksVersion = "1.41.0"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
